import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis'
import { NFTList } from '../components/NFTList'

const Home: NextPage = () => {
  const { isAuthenticated, authenticate, logout } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT-2-Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to NFT2Wallet
        </h1>
        {isAuthenticated ? 
        <div>
          <div 
                className={styles.card}
                onClick={() => {
                  logout()
                  .then(function () {
                    console.log("logged out");
                  })
                  .catch(function (error) {
                    console.log(error);
                  })
                } 
                }
              >
                <h2>Sign Out From MetaMask </h2>
              </div>
          <NFTList/> 
        </div>
          : 
          <div>
            <p className={styles.description}>
              Get started by logging in to Your Metamask wallet, so that we can list your NFTs
            </p>
            <div className={styles.grid}>
              <div 
                className={styles.card}
                onClick={() => {
                  authenticate({ signingMessage: "Authorize linking of your wallet" })
                  .then(function (user) {
                    console.log("logged in user:", user);
                  })
                  .catch(function (error) {
                    console.log(error);
                  })
                } 
                }
              >
                <h2>Sign In to Metamask</h2>
              </div>
            </div>
          </div>
        }
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
